# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度')),
                ('humid', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='湿度')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='生成日付')),
            ],
        ),
    ]
