# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_auto_20170821_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='air_cleanness',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='environment',
            name='light',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='environment',
            name='loudness',
            field=models.IntegerField(max_length=3),
        ),
    ]
