# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0012_place_has_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='co2_ppm',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
