# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0013_environment_co2_ppm'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='no_of_person',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
