# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_environment_no_of_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
